# Generated by Django 5.1.7 on 2026-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='full_name', max_length=200),
            preserve_default=False,
        ),
    ]
